name: blobDetector_Dask
channels:
  - defaults
dependencies:
  - backports.functools_lru_cache=1.5=py27_1
  - bleach=2.1.3=py27_0
  - bokeh=0.12.16=py27_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py27_0
  - cloudpickle=0.5.3=py27_0
  - dask=0.17.4=py27_0
  - dask-core=0.17.4=py27_0
  - decorator=4.3.0=py27_0
  - distributed=1.21.8=py27_0
  - heapdict=1.0.0=py27_2
  - html5lib=1.0.1=py27h5233db4_0
  - imageio=2.3.0=py27_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py27_0
  - ipython=5.7.0=py27_0
  - ipywidgets=7.2.1=py27_0
  - jupyter=1.0.0=py27_4
  - jupyter_client=5.2.3=py27_0
  - mkl=2018.0.2=1
  - networkx=2.1=py27_0
  - notebook=5.4.1=py27_0
  - olefile=0.45.1=py27_0
  - packaging=17.1=py27_0
  - pathlib2=2.3.2=py27_0
  - pexpect=4.5.0=py27_0
  - pip=10.0.1=py27_0
  - python-dateutil=2.7.3=py27_0
  - pytz=2018.4=py27_0
  - send2trash=1.5.0=py27_0
  - setuptools=39.1.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - sortedcontainers=1.5.10=py27_0
  - terminado=0.8.1=py27_1
  - toolz=0.9.0=py27_0
  - tornado=5.0.2=py27_0
  - wheel=0.31.1=py27_0
  - widgetsnbextension=3.2.1=py27_0