name: watershed_rp
channels:
  - defaults
dependencies:
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - bokeh=0.12.15
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - click=6.7
  - cloudpickle=0.5.2
  - cycler=0.10.0
  - cython=0.28.2
  - cytoolz=0.9.0.1
  - dask=0.17.2
  - dask-core=0.17.2
  - dbus=1.13.2
  - decorator=4.3.0
  - distributed=1.21.6
  - enum34=1.1.6
  - expat=2.2.5
  - fontconfig=2.12.6
  - freetype=2.8
  - functools32=3.2.3.2
  - futures=3.2.0
  - glib=2.56.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - heapdict=1.0.0
  - icu=58.2
  - imageio=2.3.0
  - intel-openmp=2018.0.0
  - ipython=5.6.0
  - ipython_genutils=0.2.0
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran-ng=7.2.0
  - libpng=1.6.34
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - locket=0.2.0
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - msgpack-python=0.5.6
  - ncurses=6.0
  - networkx=2.1
  - numpy=1.14.2
  - olefile=0.45.1
  - openssl=1.0.2o
  - packaging=17.1
  - pandas=0.22.0
  - partd=0.3.8
  - pathlib2=2.3.2
  - pcre=8.42
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=9.0.3
  - prompt_toolkit=1.0.15
  - psutil=5.4.5
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=2.7.14
  - python-dateutil=2.7.2
  - pytz=2018.4
  - pywavelets=0.5.2
  - pyyaml=3.12
  - qt=5.9.5
  - readline=7.0
  - scandir=1.7
  - scikit-image=0.13.1
  - scipy=1.0.1
  - setuptools=39.0.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - sortedcontainers=1.5.10
  - sqlite=3.23.1
  - subprocess32=3.2.7
  - tblib=1.3.2
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.31.0
  - xz=5.2.3
  - yaml=0.1.7
  - zict=0.1.3
  - zlib=1.2.11
  - pip:
    - apache-libcloud==2.3.0
    - chardet==3.0.4
    - colorama==0.3.9
    - future==0.16.0
    - idna==2.6
    - netifaces==0.10.4
    - ntplib==0.3.3
    - parse==1.8.2
    - pymongo==2.8
    - python-hostlist==1.17
    - pyzmq==17.0.0
    - radical.analytics==0.47.0
    - radical.pilot==0.47.10
    - radical.utils==0.47.4
    - requests==2.18.4
    - saga-python==0.47.3
    - setproctitle==1.1.10
    - urllib3==1.22
